### PR TITLE
Executed Excercise 0.6

### PR DESCRIPTION
**Pull request by ArpitAgrawal001**
Here's a simple flow chart:
```mermaid
sequenceDiagram
    participant Browser
    participant Server
    participant SPA

    Browser->>Server: HTTP request for https://studies.cs.helsinki.fi/exampleapp/spa
    activate Server

    Server-->>Browser: SPA files (HTML, CSS, JS) are served
    deactivate Server

    Browser->>SPA: Browser receives SPA files
    activate SPA

    SPA-->>Browser: SPA initializes and renders
    deactivate SPA

    Browser->>Server: AJAX requests for initial data/resources
    activate Server

    Server->>SPA: Initial data/resources are served
    deactivate Server
    activate SPA

    SPA-->>Browser: User creates a new note
    deactivate SPA
    Note left of SPA: Note creation action triggers an AJAX request

    Browser->>Server: AJAX request to create a new note
    activate Server
    Note right of Browser:Sends only one request

    Server-->>Browser: Confirmation of successful note creation
    deactivate Server
    Note left of Server:it responds with status code 201 created

    Browser->>SPA: SPA updates interface to display new note
    activate SPA

    SPA-->>Browser: Executed the excercise:New note in Single page app diagram
    deactivate SPA
    Note right of Browser: Exercise 0.6
```

### CODE REVIEW

**Comment by ArpitAgrawal001** [comment]
Sir as you asked me to do i have created a new feature branch from develop and pulled my develop branch in it,after that ii have done the modifications to execute excercise_0.6 properly and these are the results as follows.

Sir is it ok to merge or should i do some more modifications in it?

**Comment by ArpitAgrawal001** [comment]
image

And sir can you please tell that what i have to here?!!
(After i merge my excercise 0.6 branch)

**Review by mavenik — APPROVED** [review]
Looks okay to me. SPA sits at the browser, so I'm not sure if this can potentially miscommunicate, but it seems accurate to me.

**Comment by mavenik** [comment]
Regarding submissions, please follow instructions and get in touch with Tanmay if you face difficulty

**Comment by ArpitAgrawal001** [comment]
Ok sir

**Pull request merged**
